services:
  dev-mode:
    container_name: dev-mode
    restart: unless-stopped
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - TS_NODE_TRANSPILE_ONLY=1
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - ./src:/app/src

  prod-mode:
    container_name: prod-mode
    restart: unless-stopped
    build:
      target: prod
      context: .
    ports:
      - "3000:3000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate --url http://prod-mode:3000
    restart: unless-stopped
